name: ticker
region: fra
services:
  - name: web
    github:
      repo: YOUR_GITHUB_USERNAME/B5Todo
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    envs:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        type: SECRET
        value: "${APP_KEY}"
      - key: APP_URL
        value: "${APP_URL}"
      - key: DATABASE_URL
        value: "${db.DATABASE_URL}"
      - key: DB_CONNECTION
        value: pgsql
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 80

databases:
  - name: db
    engine: PG
    production: false
    version: "15"
